--- #YAML:1.0
name:                Geo-Coordinates-OSGB
version:             2.02
abstract:            Convert Coordinates from Lat/Long to UK Grid
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.3201
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
